---
resource_types:
- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest

groups:
- name: release
  jobs:
    - push-apps
    - map-green-to-blue
    - unmap-blue
    - clean-up
- name: destroy
  jobs:
    - destroy

jobs:
- name: destroy
  plan:
  - aggregate:
    - put: delete-blue
      resource: cf-env
      params:
        command: delete
        app_name: spring-music
        delete_mapped_routes: true
    - put: delete-green
      resource: cf-env
      params:
        command: delete
        app_name: spring-music-new
        delete_mapped_routes: true

- name: push-apps
  serial: true
  plan:
  - get: repo
  - aggregate:
    - put: push-blue
      resource: cf-env
      params:
        command: push
        app_name: spring-music
        hostname: spring-music-((cf-space))
        memory: 2G
        path: repo/pcf-basics/spring-music-blue.jar
        buildpack: https://github.com/cloudfoundry/java-buildpack.git
        environment_variables:
          TRUST_CERTS: ((cf-api-uri))
    - put: push-green
      resource: cf-env
      params:
       command: push
       app_name: spring-music-new
       hostname: spring-music-((cf-space))-temp
       memory: 2G
       path: repo/pcf-basics/spring-music-green.jar
       buildpack: https://github.com/cloudfoundry/java-buildpack.git
       environment_variables:
         TRUST_CERTS: ((cf-api-uri))

- name: map-green-to-blue
  serial: true
  plan:
  - get: repo
    passed: [ push-apps ]
  - put: map-green-to-blue
    resource: cf-env
    params:
      command: map-route
      app_name: spring-music-new
      domain: ((cf-domain))
      hostname: spring-music-((cf-space))

- name: unmap-blue
  serial: true
  plan:
  - get: repo
    passed: [ map-green-to-blue ]
  - put: unmap-blue
    resource: cf-env
    params:
      command: unmap-route
      app_name: spring-music
      domain: ((cf-domain))
      hostname: spring-music-((cf-space))

- name: clean-up
  serial: true
  plan:
  - get: repo
    passed: [ unmap-blue ]
  - put: delete-temp-route
    resource: cf-env
    params:
      command: delete-route
      domain: ((cf-domain))
      hostname: spring-music-((cf-space))-temp
  - put: delete-blue
    resource: cf-env
    params:
      command: delete
      app_name: spring-music
      delete_mapped_routes: true
  - put: rename-green
    resource: cf-env
    params:
      command: rename
      app_name: spring-music-new
      new_app_name: spring-music

resources:
- name: repo
  type: git
  source:
    uri: ((git-uri))
    branch: ((git-branch))
- name: cf-env
  type: cf-cli-resource
  source:
    api: ((cf-api-uri))
    username: ((cf-username))
    password: ((cf-password))
    org: ((cf-org))
    space: ((cf-space))
